### ISSUE TITLE
webfist fallback is broken

### ISSUE THREAD

**Issue by willnorris** [webfinger/client.webfinger.net#4]
The webfist fallback isn't currently working, instead reporting a `DEADLINE_EXCEEDED` error (eg: http://client.webfinger.net/lookup?resource=wnorris%40gmail.com).  This is happening because webfist.org still does not listen on https.  The go-webfinger library will fallback to http in this case, but this deadline exceeded error seems to be preventing it.

**Comment by aaronpk** [comment]
webfist.org appears to be entirely down now. Maybe it should be removed from the site?
