### ISSUE TITLE
The 'template' key is not displayed.

### ISSUE THREAD

**Issue by zoowar** [webfinger/client.webfinger.net#8]
At least one entry has a template key, which the tool is not displaying.

    {"rel": "http://ostatus.org/schema/1.0/subscribe",
     "template": "https://example.com/{url}"}

**Comment by willnorris** [comment]
`template` is not part of the JRD spec: https://tools.ietf.org/html/rfc7033#section-4.4.4

**Comment by willnorris** [comment]
Do you have an example document that includes this?

**Comment by zoowar** [comment]
Feel free to close this, as "template" is not part of the spec as you have demonstrated. In any case, it is part of the OStatus protocol, which I'm not advocating. A live example can be found [here](https://social.umeahackerspace.se/.well-known/webfinger?resource=acct%3Ammn%40social.umeahackerspace.se)

**Comment by willnorris** [comment]
huh, interesting.  @evanp, do you recall why that is?  I forget, did a previous draft of webfinger include template and maybe that's what OStatus was using?

**Comment by willnorris** [comment]
Ah, yeah I think that's it.  Earlier versions of WebFinger were based on [XRD](http://docs.oasis-open.org/xri/xrd/v1.0/xrd-1.0.html) which did include a `template`, but it was later removed from WebFinger/JRD.  [Searching the mailing list archives](https://groups.google.com/forum/#!searchin/webfinger/template%7Csort:relevance) shows several discussions about this which I had actually forgotten about.

**Comment by evanp** [comment]
There you go
